name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.1'
        
    - name: Build all apps
      run: make build
      
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: bin/*
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}